### ISSUE TITLE
Age verification doesn't work on a Mobile Device

### ISSUE THREAD

**Issue by iaholyk** [stevemeisner/age-verification#1]
First off, the check box button to finish a form field or be done with the form all together, on your phones keyboard doesn't work.  So each time you click a section of the form i.e. month, and are done filling it out, you have to retract your phones keyboard to fill out the next section of the form i.e. day.  When you do this the form itself, jumps down on the screen, so that the form fields are no longer visible at all.  When you try to move the form back up you cannot because the position is fixed.  This Age Verification will not let users into the site from a mobile phone.

**Comment by SebastienGens** [comment]
It works fine on a mobile device from my side, the design is responsive and fully working (implementation done on a weebly website).

Also, there is no form in this code, so you might not have posted your comment on the right repository.

**Comment by iaholyk** [comment]
This is the one that works it is the other one with the form feilds.

http://www.jqueryscript.net/other/Html5-sessionStorage-Based-Age-Verification-with-jQuery-Age-Check.html
-  Isaac Holyk   *
  -  Lead Software Designer    *
  -  C.E.O.   *
  -     Cell- (360) 980-0618          *

**Comment by iaholyk** [comment]
It is the michealsoriano age verification Frickinawesomesteves works just
fine
-  Isaac Holyk   *
  -  Lead Software Designer    *
  -  C.E.O.   *
  -     Cell- (360) 980-0618          *
