### ISSUE TITLE
The buttons are not centered on a mobile device

### ISSUE THREAD

**Issue by SebastienGens** [stevemeisner/age-verification#3]
Is there a way to fix this?
Thanks!

**Comment by stevemeisner** [comment]
Sebastian, I'll look into it!

**Comment by stevemeisner** [comment]
Sebastian,

What is your expectation for a mobile device? This is a screenshot from a screen resolution that's the same as the iPhone 5.

![mobile view](http://i.imgbox.com/CU8TPOw4.png)

**Comment by SebastienGens** [comment]
I didn't take the time to fix it myself but that looks right!
Thanks

**Comment by stevemeisner** [comment]
I didn't actually make any changes to the css, I just went and tested it as is. Are you seeing your desired results now?

**Comment by SebastienGens** [comment]
So it is probably only a problem on my side since I might have changed the size of the buttons or something. I'll investigate it.

Thanks!

**Comment by stevemeisner** [comment]
Ok. Sounds good!

**Comment by SebastienGens** [comment]
It seems like the problem comes from the fact that I changed the size of the circle from 290px to 330px.

```
width: 330px; /* originalmente 290 */ 
height: 330px; /* originalmente 290 */
```

Any idea on how to center the buttons again with this size? I tried a bunch of things but nothing worked. Is anything related to these centered buttons fixed in the design? 

Thanks!

**Comment by SebastienGens** [comment]
I just solved the problem and suggested to add a comment on the css to clarify what needs to be edited if a user wants to change the size of the rounded pop-up (via a pull request on Github)

;p

**Comment by stevemeisner** [comment]
Fantastic! Pardon me while I blush at the sight of my own unclosed tags.....

**Comment by SebastienGens** [comment]
No worries, it was apparently a typing mistake ;p
Have a good day!

_--_
_Sébastien Gens_
http://www.linkedin.com/in/sebastiengens
_@Twitter https://twitter.com/SebastienGens_
