### ISSUE TITLE
Shouldn´t this repository be under Javascript instead of HTML?

### ISSUE THREAD

**Issue by SebastienGens** [stevemeisner/age-verification#4]

**Comment by stevemeisner** [comment]
Sure, I guess. Sounds good to me! I'll see about changing it.

**Comment by stevemeisner** [comment]
So I learned something this evening!

Github auto-detects your repo and decides on it's type programmatically.

https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/
https://github.com/github/linguist#troubleshooting

Looks like I can heavy-handedly try and override it, but it's not a huge priority for me right now. It's good to know how this works, though! Maybe one day.

Thanks for pointing it out.
